Traceback (most recent call last):
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1817, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/apps/python/3.10-anaconda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 51, in <module>
    from .loss.loss_utils import LOSS_MAPPING
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/transformers/loss/loss_utils.py", line 19, in <module>
    from .loss_deformable_detr import DeformableDetrForObjectDetectionLoss, DeformableDetrForSegmentationLoss
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/transformers/loss/loss_deformable_detr.py", line 4, in <module>
    from ..image_transforms import center_to_corners_format
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/transformers/image_transforms.py", line 22, in <module>
    from .image_utils import (
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/transformers/image_utils.py", line 59, in <module>
    from torchvision.transforms import InterpolationMode
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/torchvision/__init__.py", line 10, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/torchvision/_meta_registrations.py", line 164, in <module>
    def meta_nms(dets, scores, iou_threshold):
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/torch/library.py", line 828, in register
    use_lib._register_fake(op_name, func, _stacklevel=stacklevel + 1)
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/torch/library.py", line 198, in _register_fake
    handle = entry.fake_impl.register(func_to_register, source)
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/torch/_library/fake_impl.py", line 31, in register
    if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
RuntimeError: operator torchvision::nms does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hpc/mrrr/mrrr120v/paper07_Self-Rectification/main.py", line 5, in <module>
    from diffusers import DDIMScheduler
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/diffusers/__init__.py", line 36, in <module>
    from .models import (
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/diffusers/models/__init__.py", line 20, in <module>
    from .controlnet import ControlNetModel
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/diffusers/models/controlnet.py", line 32, in <module>
    from .unet_2d_condition import UNet2DConditionModel
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 23, in <module>
    from ..loaders import UNet2DConditionLoadersMixin
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/diffusers/loaders.py", line 37, in <module>
    from transformers import PreTrainedModel, PreTrainedTokenizer
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1805, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/hpc/mrrr/mrrr120v/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1819, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
operator torchvision::nms does not exist
